services:
  d01-py-for-dt:
    image: d01-py-for-dt:42
    container_name: d01-py-for-dt
    init: true
    build:
      context: requirements/d01-py-for-dt
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
