services:
  d02-py-for-dt:
    image: d02-py-for-dt:42
    container_name: d02-py-for-dt
    init: true
    build:
      context: requirements/D02-py-for-dt
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
